apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-consul
  namespace: {{ .Namespace }}
  labels:
    app: consul
spec:
  ports:
    - name: http
      port: 8500
    - name: rpc
      port: 8400
    - name: tcp-serflan
      protocol: "TCP"
      port: 8301
    - name: udp-serflan
      protocol: "UDP"
      port: 8301
    - name: tcp-serfwan
      protocol: "TCP"
      port: 8302
    - name: udp-serfwan
      protocol: "UDP"
      port: 8302
    - name: server
      port: 8300
    - name: consuldns
      port: 8600
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: consul
