---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8s.jhipster.tech
  resources:
  - jhipsterapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.jhipster.tech
  resources:
  - jhipsterapplications/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.jhipster.tech
  resources:
  - jhipsterapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.jhipster.tech
  resources:
  - jhipstersetups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.jhipster.tech
  resources:
  - jhipstersetups/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.jhipster.tech
  resources:
  - jhipstersetups/status
  verbs:
  - get
  - patch
  - update
