## Append samples you want in your CSV to this file as resources ##
resources:
- k8s_v1alpha1_jhipstersetup.yaml
- k8s_v1alpha1_jhipsterapplication.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
