//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfiguration) DeepCopyInto(out *DatabaseConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfiguration.
func (in *DatabaseConfiguration) DeepCopy() *DatabaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JHipsterApplication) DeepCopyInto(out *JHipsterApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JHipsterApplication.
func (in *JHipsterApplication) DeepCopy() *JHipsterApplication {
	if in == nil {
		return nil
	}
	out := new(JHipsterApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JHipsterApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JHipsterApplicationList) DeepCopyInto(out *JHipsterApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JHipsterApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JHipsterApplicationList.
func (in *JHipsterApplicationList) DeepCopy() *JHipsterApplicationList {
	if in == nil {
		return nil
	}
	out := new(JHipsterApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JHipsterApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JHipsterApplicationSpec) DeepCopyInto(out *JHipsterApplicationSpec) {
	*out = *in
	if in.IngressDomain != nil {
		in, out := &in.IngressDomain, &out.IngressDomain
		*out = new(string)
		**out = **in
	}
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	out.DatabaseConfiguration = in.DatabaseConfiguration
	if in.ServiceType != nil {
		in, out := &in.ServiceType, &out.ServiceType
		*out = new(v1.ServiceType)
		**out = **in
	}
	in.ApplicationOverrides.DeepCopyInto(&out.ApplicationOverrides)
	in.DatabaseOverrides.DeepCopyInto(&out.DatabaseOverrides)
	in.IngressOverrides.DeepCopyInto(&out.IngressOverrides)
	in.ServiceOverrides.DeepCopyInto(&out.ServiceOverrides)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JHipsterApplicationSpec.
func (in *JHipsterApplicationSpec) DeepCopy() *JHipsterApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(JHipsterApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JHipsterApplicationStatus) DeepCopyInto(out *JHipsterApplicationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JHipsterApplicationStatus.
func (in *JHipsterApplicationStatus) DeepCopy() *JHipsterApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(JHipsterApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JHipsterSetup) DeepCopyInto(out *JHipsterSetup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JHipsterSetup.
func (in *JHipsterSetup) DeepCopy() *JHipsterSetup {
	if in == nil {
		return nil
	}
	out := new(JHipsterSetup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JHipsterSetup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JHipsterSetupList) DeepCopyInto(out *JHipsterSetupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JHipsterSetup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JHipsterSetupList.
func (in *JHipsterSetupList) DeepCopy() *JHipsterSetupList {
	if in == nil {
		return nil
	}
	out := new(JHipsterSetupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JHipsterSetupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JHipsterSetupSpec) DeepCopyInto(out *JHipsterSetupSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JHipsterSetupSpec.
func (in *JHipsterSetupSpec) DeepCopy() *JHipsterSetupSpec {
	if in == nil {
		return nil
	}
	out := new(JHipsterSetupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JHipsterSetupStatus) DeepCopyInto(out *JHipsterSetupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JHipsterSetupStatus.
func (in *JHipsterSetupStatus) DeepCopy() *JHipsterSetupStatus {
	if in == nil {
		return nil
	}
	out := new(JHipsterSetupStatus)
	in.DeepCopyInto(out)
	return out
}
